### ISSUE TITLE
problem with _hx_register_type() 

### ISSUE THREAD

**Issue by francescoagati** [benmerckx/packphp#1]
Hi. with erazor and other libraries i get this error

```
Call to undefined function _hx_register_type() 
```

because  _hx_register_type()  is defined after the classe definitions. I think that php_boot should be always on top of header file

**Comment by benmerckx** [comment]
Hey, could you make sure you're using the very last version (0.0.4)? Because php_Boot should be included at the top: https://github.com/benmerckx/packphp/blob/master/PackPHP.hx#L108

**Comment by francescoagati** [comment]
hey yes i use the 4.0.4 i have forked the project for  try to dump the order of the classes for see what is the problem.

**Comment by francescoagati** [comment]
This is the dump of classes sorted in my project, the classes are all prefixed with wdg

```
PackPHP.hx:85: lib_wdgStringBuf,0
PackPHP.hx:85: lib_wdgStringTools,0
PackPHP.hx:85: lib_wdgEReg,0
PackPHP.hx:85: lib_thx_wdgStrings,0
PackPHP.hx:85: lib_thx__QueryString_wdgQueryStringValue_Impl_,0
PackPHP.hx:85: lib_thx__QueryString_wdgQueryString_Impl_,0
PackPHP.hx:85: lib_thx_wdgArrays,0
PackPHP.hx:85: lib_thx_wdgObjects,0
PackPHP.hx:85: lib_thx_wdgFunctions,0
PackPHP.hx:85: lib_thx_wdgFunctions1,0
PackPHP.hx:85: lib_thx_wdgTypes,0
PackPHP.hx:85: lib_thx__Url_wdgUrl_Impl_,0
PackPHP.hx:85: lib_thx_wdgFunctions0,0
PackPHP.hx:85: lib_thx_wdgArrayStrings,0
PackPHP.hx:85: lib_thx_wdgArrayInts,0
PackPHP.hx:85: lib_thx_wdgMaps,0
PackPHP.hx:85: lib_thx_wdgIterables,0
PackPHP.hx:85: lib_thx__Tuple_wdgTuple3_Impl_,0
PackPHP.hx:85: lib_thx__Tuple_wdgTuple1_Impl_,0
PackPHP.hx:85: lib_thx__Tuple_wdgTuple0_Impl_,0
PackPHP.hx:85: lib_thx__Tuple_wdgTuple4_Impl_,0
PackPHP.hx:85: lib_thx__Tuple_wdgTuple6_Impl_,0
PackPHP.hx:85: lib_thx__Tuple_wdgTuple5_Impl_,0
PackPHP.hx:85: lib_thx__Tuple_wdgTuple2_Impl_,0
PackPHP.hx:85: lib_thx_wdgInts,0
PackPHP.hx:85: lib_thx_wdgError,0
PackPHP.hx:85: lib_thx_wdgIterators,0
PackPHP.hx:85: lib_thx_wdgFunctions3,0
PackPHP.hx:85: lib_thx_wdgArrayFloats,0
PackPHP.hx:85: lib_thx_wdgNulls,0
PackPHP.hx:85: lib_thx_wdgDynamics,0
PackPHP.hx:85: lib_thx_wdgFunctions2,0
PackPHP.hx:85: lib_wdgStd,0
PackPHP.hx:85: lib_php_wdgLib,0
PackPHP.hx:85: lib_wdgType,0
PackPHP.hx:85: lib_apps_prj_site_wdgTestRouter,0
PackPHP.hx:85: lib_wdgDate,0
PackPHP.hx:85: lib_wdgIMap,0
PackPHP.hx:85: lib_haxe_wdgCallStack,0
PackPHP.hx:85: lib_haxe_wdgJson,0
PackPHP.hx:85: lib_haxe_web_wdgRedirect,0
PackPHP.hx:85: lib_haxe_web_wdgDispatch,0
PackPHP.hx:85: lib_haxe_wdgHttp,0
PackPHP.hx:85: lib_haxe_rtti_wdgMeta,0
PackPHP.hx:85: lib_haxe_wdgUnserializer,0
PackPHP.hx:85: lib_haxe_io_wdgBytes,0
PackPHP.hx:85: lib_haxe_io_wdgEof,0
PackPHP.hx:85: lib_haxe_io_wdgInput,0
PackPHP.hx:85: lib_haxe_io_wdgBytesBuffer,0
PackPHP.hx:85: lib_haxe_io_wdgOutput,0
PackPHP.hx:85: lib_haxe_wdgUtf8,0
PackPHP.hx:85: lib_haxe_ds_wdgObjectMap,0
PackPHP.hx:85: lib_haxe_ds_wdgStringMap,0
PackPHP.hx:85: lib_haxe_ds_wdgIntMap,0
PackPHP.hx:85: lib_haxe_format_wdgJsonPrinter,0
PackPHP.hx:85: lib_haxe_wdgLog,0
PackPHP.hx:85: lib_wdgHList,0
PackPHP.hx:85: lib_lib__DynamicObject_wdgDynamicObject_Impl_,0
PackPHP.hx:85: lib_lib_wdgArrayTools,0
PackPHP.hx:85: lib_lib_prj_wdgWidgetSkins,0
PackPHP.hx:85: lib_lib_prj_wdgPanel,0
PackPHP.hx:85: lib_lib_prj_wdgPanelItemTools,0
PackPHP.hx:85: lib_lib_prj_wdgWidgetRestRouter,0
PackPHP.hx:85: lib_lib_prj_wdgPanelBuilder,0
PackPHP.hx:85: lib_lib_prj_wdgPanelPaths,0
PackPHP.hx:85: lib_lib_prj_api_wdgApiCategory,0
PackPHP.hx:85: lib_lib_prj__Panel_wdgAPanelType_Impl_,0
PackPHP.hx:85: lib_lib_wdgWidgetTools,0
PackPHP.hx:85: lib_lib__Widget_wdgAWidget_Impl_,0
PackPHP.hx:85: lib_lib_wdgGUID,0
PackPHP.hx:85: lib_lib_wdgDynamicObjectTools,0
PackPHP.hx:85: lib_lib_wdgHttpHelper,0
PackPHP.hx:85: lib_lib_wdgDebugger,0
PackPHP.hx:85: lib_promhx_base_wdgEventLoop,0
PackPHP.hx:85: lib_promhx_base_wdgAsyncBase,0
PackPHP.hx:85: lib_wdgReflect,0
PackPHP.hx:85: lib_wdgLambda,0
PackPHP.hx:85: lib_wdgMath,0
PackPHP.hx:85: lib_sys_net_wdgHost,0
PackPHP.hx:85: lib_sys_net_wdgSocket,0
PackPHP.hx:85: lib_thx_wdgNil,1
PackPHP.hx:85: lib_thx_error_wdgErrorWrapper,1
PackPHP.hx:85: lib_php_net_wdgSslSocket,1
PackPHP.hx:85: lib_php_wdgBoot,1
PackPHP.hx:85: lib_haxe_wdgStackItem,1
PackPHP.hx:85: lib_haxe_web_wdgDispatchError,1
PackPHP.hx:85: lib_haxe_web_wdgMatchRule,1
PackPHP.hx:85: lib_haxe_web_wdgDispatchRule,1
PackPHP.hx:85: lib_haxe_io_wdgBytesOutput,1
PackPHP.hx:85: lib_haxe_io_wdgError,1
PackPHP.hx:85: lib_haxe_ds_wdgOption,1
PackPHP.hx:85: lib_wdgValueType,1
PackPHP.hx:85: lib_lib_wdgTargetFactory,1
PackPHP.hx:85: lib_lib_wdgColorSchemaFactory,1
PackPHP.hx:85: lib_lib_prj_wdgSkinType,1
PackPHP.hx:85: lib_lib_prj_wdgTokens,1
PackPHP.hx:85: lib_lib_prj_wdgPanelType,1
PackPHP.hx:85: lib_lib_wdgTargetTokenFactory,1
PackPHP.hx:85: lib_lib_wdgWidgetFactory,1
PackPHP.hx:85: lib_lib_wdgPanelFactory,1
PackPHP.hx:85: lib_promhx_wdgPromise,1
PackPHP.hx:85: lib_promhx_wdgDeferred,1
PackPHP.hx:85: lib_promhx_wdgPublicStream,1
PackPHP.hx:85: lib_promhx_deferred_wdgDeferredPromise,1
PackPHP.hx:85: lib_promhx_error_wdgPromiseError,1
PackPHP.hx:85: lib_promhx_wdgStream,1
PackPHP.hx:85: lib_sys_io_wdgFileInput,1
PackPHP.hx:85: lib_sys_io_wdgFileOutput,1
PackPHP.hx:85: lib_sys_io_wdgFileHandle,1

```

and without prefix 

```
PackPHP.hx:85: lib_Lambda,0
PackPHP.hx:85: lib_Std,0
PackPHP.hx:85: lib_Date,0
PackPHP.hx:85: lib_thx_Error,0
PackPHP.hx:85: lib_thx__QueryString_QueryString_Impl_,0
PackPHP.hx:85: lib_thx__QueryString_QueryStringValue_Impl_,0
PackPHP.hx:85: lib_thx_Iterables,0
PackPHP.hx:85: lib_thx_Arrays,0
PackPHP.hx:85: lib_thx_Functions,0
PackPHP.hx:85: lib_thx_Functions0,0
PackPHP.hx:85: lib_thx_Functions3,0
PackPHP.hx:85: lib_thx_ArrayFloats,0
PackPHP.hx:85: lib_thx__Url_Url_Impl_,0
PackPHP.hx:85: lib_thx_Iterators,0
PackPHP.hx:85: lib_thx_ArrayStrings,0
PackPHP.hx:85: lib_thx_Maps,0
PackPHP.hx:85: lib_thx_Strings,0
PackPHP.hx:85: lib_thx_Functions2,0
PackPHP.hx:85: lib_thx_Dynamics,0
PackPHP.hx:85: lib_thx__Tuple_Tuple4_Impl_,0
PackPHP.hx:85: lib_thx__Tuple_Tuple6_Impl_,0
PackPHP.hx:85: lib_thx__Tuple_Tuple3_Impl_,0
PackPHP.hx:85: lib_thx__Tuple_Tuple2_Impl_,0
PackPHP.hx:85: lib_thx__Tuple_Tuple0_Impl_,0
PackPHP.hx:85: lib_thx__Tuple_Tuple5_Impl_,0
PackPHP.hx:85: lib_thx__Tuple_Tuple1_Impl_,0
PackPHP.hx:85: lib_thx_Ints,0
PackPHP.hx:85: lib_thx_Nulls,0
PackPHP.hx:85: lib_thx_Objects,0
PackPHP.hx:85: lib_thx_ArrayInts,0
PackPHP.hx:85: lib_thx_Functions1,0
PackPHP.hx:85: lib_thx_Types,0
PackPHP.hx:85: lib_IMap,0
PackPHP.hx:85: lib_php_Lib,0
PackPHP.hx:85: lib_StringTools,0
PackPHP.hx:85: lib_Math,0
PackPHP.hx:85: lib_Reflect,0
PackPHP.hx:85: lib_StringBuf,0
PackPHP.hx:85: lib_apps_prj_site_TestRouter,0
PackPHP.hx:85: lib_haxe_web_Dispatch,0
PackPHP.hx:85: lib_haxe_web_Redirect,0
PackPHP.hx:85: lib_haxe_CallStack,0
PackPHP.hx:85: lib_haxe_Utf8,0
PackPHP.hx:85: lib_haxe_rtti_Meta,0
PackPHP.hx:85: lib_haxe_io_Bytes,0
PackPHP.hx:85: lib_haxe_io_Output,0
PackPHP.hx:85: lib_haxe_io_BytesBuffer,0
PackPHP.hx:85: lib_haxe_io_Eof,0
PackPHP.hx:85: lib_haxe_io_Input,0
PackPHP.hx:85: lib_haxe_Log,0
PackPHP.hx:85: lib_haxe_Http,0
PackPHP.hx:85: lib_haxe_Unserializer,0
PackPHP.hx:85: lib_haxe_ds_IntMap,0
PackPHP.hx:85: lib_haxe_ds_ObjectMap,0
PackPHP.hx:85: lib_haxe_ds_StringMap,0
PackPHP.hx:85: lib_haxe_format_JsonPrinter,0
PackPHP.hx:85: lib_haxe_Json,0
PackPHP.hx:85: lib_EReg,0
PackPHP.hx:85: lib_lib_WidgetTools,0
PackPHP.hx:85: lib_lib__DynamicObject_DynamicObject_Impl_,0
PackPHP.hx:85: lib_lib_DynamicObjectTools,0
PackPHP.hx:85: lib_lib_HttpHelper,0
PackPHP.hx:85: lib_lib_prj_PanelItemTools,0
PackPHP.hx:85: lib_lib_prj_Panel,0
PackPHP.hx:85: lib_lib_prj_PanelBuilder,0
PackPHP.hx:85: lib_lib_prj_WidgetRestRouter,0
PackPHP.hx:85: lib_lib_prj_api_ApiCategory,0
PackPHP.hx:85: lib_lib_prj_WidgetSkins,0
PackPHP.hx:85: lib_lib_prj_PanelPaths,0
PackPHP.hx:85: lib_lib_prj__Panel_APanelType_Impl_,0
PackPHP.hx:85: lib_lib_Debugger,0
PackPHP.hx:85: lib_lib__Widget_AWidget_Impl_,0
PackPHP.hx:85: lib_lib_GUID,0
PackPHP.hx:85: lib_lib_ArrayTools,0
PackPHP.hx:85: lib_promhx_base_EventLoop,0
PackPHP.hx:85: lib_promhx_base_AsyncBase,0
PackPHP.hx:85: lib_Type,0
PackPHP.hx:85: lib_HList,0
PackPHP.hx:85: lib_sys_net_Host,0
PackPHP.hx:85: lib_sys_net_Socket,0
PackPHP.hx:85: lib_thx_Nil,1
PackPHP.hx:85: lib_thx_error_ErrorWrapper,1
PackPHP.hx:85: lib_ValueType,1
PackPHP.hx:85: lib_php_net_SslSocket,1
PackPHP.hx:85: lib_php_Boot,1
PackPHP.hx:85: lib_haxe_web_DispatchRule,1
PackPHP.hx:85: lib_haxe_web_MatchRule,1
PackPHP.hx:85: lib_haxe_web_DispatchError,1
PackPHP.hx:85: lib_haxe_StackItem,1
PackPHP.hx:85: lib_haxe_io_BytesOutput,1
PackPHP.hx:85: lib_haxe_io_Error,1
PackPHP.hx:85: lib_haxe_ds_Option,1
PackPHP.hx:85: lib_lib_PanelFactory,1
PackPHP.hx:85: lib_lib_prj_SkinType,1
PackPHP.hx:85: lib_lib_prj_Tokens,1
PackPHP.hx:85: lib_lib_prj_PanelType,1
PackPHP.hx:85: lib_lib_TargetFactory,1
PackPHP.hx:85: lib_lib_ColorSchemaFactory,1
PackPHP.hx:85: lib_lib_TargetTokenFactory,1
PackPHP.hx:85: lib_lib_WidgetFactory,1
PackPHP.hx:85: lib_promhx_Deferred,1
PackPHP.hx:85: lib_promhx_PublicStream,1
PackPHP.hx:85: lib_promhx_deferred_DeferredPromise,1
PackPHP.hx:85: lib_promhx_error_PromiseError,1
PackPHP.hx:85: lib_promhx_Stream,1
PackPHP.hx:85: lib_promhx_Promise,1
PackPHP.hx:85: lib_sys_io_FileOutput,1
PackPHP.hx:85: lib_sys_io_FileHandle,1
PackPHP.hx:85: lib_sys_io_FileInput,1


```

**Comment by benmerckx** [comment]
Hey thanks! I'll change the code so it accounts for the prefixes in php_Boot.

**Comment by francescoagati** [comment]
i try to do  a little modificaton. but my code is really ugly. and don't resolve all the problems i think.

```
  classes.sort(function(a, b) {
      return getPosition(classMap, a.name) - getPosition(classMap, b.name);
    });



    var pos = 0;
    var cnt = 0;
    for (cls in classes) {
      cnt++;
      if (cls.name.indexOf('php_Boot') >= 0) {pos = cnt;}
    }

    var boot = classes[pos-1];
    trace(boot);
    var arr = [];

    cnt = 0;
    for(cls in classes) {
      cnt++;
      if (cls.name.indexOf('php_Boot') == -1)  arr.push(cls);
    }

    arr.unshift(boot);
    classes = arr;

    //for(cls in classes) trace(cls.name,getPosition(classMap,cls.name));


    body = body.replace(
      "require_once dirname(__FILE__).'/"+info.lib+"php/"+info.prefix+"Boot.class.php';",
      [for (item in classes) {
        var output = '';
        if (item.name.indexOf('php_Boot') == -1 )
          output += '\n_hx_register_type(new _hx_${phpType(item.type)}("${item.name}", "${item.name.split("_").join(".")}", "${main}"));';
        output += item.body;
      }].join('\n')
    );
```

**Comment by benmerckx** [comment]
I've updated the code so it should recognize php_Boot even with a prefix. It's not perfect but should work. New version is on haxelib.
I do see in your output it traces 'lib_php_Boot' so it might still fail because in my test cases I get 'php_Boot'. That maybe happens because I assumed two packages here: https://github.com/benmerckx/packphp/blob/master/PackPHP.hx#L138

Could you share your hxml file if things still fail?

**Comment by benmerckx** [comment]
Ok, things fail here if I use `-php one/two` (two dirs deep). I'll check if I can get this fixed.

**Comment by benmerckx** [comment]
Things should compile using 0.0.6, I've added a check if using more than one directory in -php

**Comment by francescoagati** [comment]
yes with the 0.0.6 it works correctly now. thanks :-).
Also with php-prefix

**Comment by francescoagati** [comment]
my hxml file

--next
-main apps.prj.TestRouter
-php  www/test
--php-front test.php
--php-prefix pippa
-lib packphp compiletime continuation promhx thx.core tink_macro erazor
-dce full

**Comment by francescoagati** [comment]
i have notice another bug now. with haxe.web.dispatch an php-prefix.
i get this error 

```
uncaught exception: Enum not found haxe.web.DispatchRule

in file: /home/francesco/projects/veespo_connect/www/test/test.php line 2272
#0 /home/francesco/projects/veespo_connect/www/test/test.php(2126): haxe_pippssUnserializer->unserialize()
#1 /home/francesco/projects/veespo_connect/www/test/test.php(2227): haxe_pippssUnserializer->unserializeObject(Object(_hx_anonymous))
#2 /home/francesco/projects/veespo_connect/www/test/test.php(2455): haxe_pippssUnserializer->unserialize()
#3 /home/francesco/projects/veespo_connect/www/test/test.php(1929): haxe_pippssUnserializer::run('oy4:langjy21:ha...')

```

this the dispatch serialized

```
:$__meta__ = _hx_anonymous(array("obj" => _hx_anonymous(array("dispatchConfig" => (new _hx_array(array("oy4:langjy21:haxe.web.DispatchRule:1:1ajy18:haxe.web.MatchRule:5:0jR2:3:0hy4:skinjR1:1:1ajR2:5:0jR2:3:0hy13:target_createjR1:1:1ajR2:5:0jR2:3:0hy7:partnerjR1:1:1ajR2:5:0jR2:3:0hy5:shortjR1:1:1ajR2:5:0jR2:3:0jR2:3:0jR2:3:0hy7:versionjR1:1:1ajR2:5:0jR2:3:0hy3:getjR1:2:3jR1:0:1jR2:5:0aoy4:namey7:bgcolory4:rulejR2:3:0y3:opttgoR9y5:colorR11jR2:3:0R12tgoR9y6:createR11jR2:1:0R12tgoR9y9:hidePanelR11jR2:1:0R12tgoR9y9:hideTitleR11jR2:1:0R12tgoR9y4:key1R11jR2:3:0R12tgoR9y4:key2R11jR2:3:0R12tgoR9y4:key3R11jR2:3:0R12tgoR9y4:key4R11jR2:3:0R12tgoR9y4:key5R11jR2:3:0R12tgoR9y10:panelcolorR11jR2:3:0R12tgoR9y5:thumbR11jR2:3:0R12tgoR9y5:titleR11jR2:3:0R12tgoR9y5:tokenR11jR2:3:0R12tgoR9y4:userR11jR2:3:0R12tghfy5:mediajR1:1:1ajR2:5:0jR2:3:0jR2:3:0hy6:targetjR1:1:1ajR2:5:0jR2:3:0hR24jR1:1:1ajR2:5:0jR2:3:0hy7:defaultjR1:1:1ahy8:categoryjR1:1:1ajR2:5:0jR2:3:0hg")))))));
```

and this the code generated from packphp of class dispatchrule

```
_hx_register_type(new _hx_enum("haxe_web_pippssDispatchRule", "haxe.web.pippssDispatchRule", "www/test/test.php"));
class haxe_web_pippssDispatchRule extends Enum {
    public static function DRArgs($r, $args, $opt) { return new haxe_web_pippssDispatchRule("DRArgs", 2, array($r, $args, $opt)); }
    public static function DRMatch($r) { return new haxe_web_pippssDispatchRule("DRMatch", 0, array($r)); }
    public static function DRMeta($r) { return new haxe_web_pippssDispatchRule("DRMeta", 3, array($r)); }
    public static function DRMult($r) { return new haxe_web_pippssDispatchRule("DRMult", 1, array($r)); }
    public static $__constructors = array(2 => 'DRArgs', 0 => 'DRMatch', 3 => 'DRMeta', 1 => 'DRMult');
    }

```

i think that webdispatchrule don't work good with prefix-php if the class isnt' load from autoload php.
